### PR TITLE
Move syncing test-openshift.yaml as soon as the file is in dist-git

### PR DESCRIPTION
**Pull request by phracek**
This pull request moves to modify test-openshift.yaml content
in dist-git repositories and not in upstream.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
@pkubatrh Does it make sense to you? It means, that test-openshift.yaml is modified only in dist-git repositories and not in upstream repository.

**Comment by pkubatrh** [comment]
lgtm

**Pull request merged**
