### PR TITLE
Fix for 'src_path_content' in upstream does not exist

### PR DESCRIPTION
**Pull request by phracek**
Fix for 'src_path_content' in upstream does not exist
like was removed by PR,
then 'os.readlink(src_path_content)' failed with
traceback 'FileNotFoundError'.

See real error:
```
rh_cwt.main.distgit - DEBUG: unlink nginx-124/results/test/run-openshift Traceback (most recent call last):
  File "/usr/local/bin/rhcwt", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/phracek/.local/lib/python3.12/site-packages/rh_cwt/cli.py", line 169, in run
    cli.run()
  File "/home/phracek/.local/lib/python3.12/site-packages/rh_cwt/cli.py", line 163, in run
    run_function()
  File "/home/phracek/.local/lib/python3.12/site-packages/rh_cwt/main.py", line 369, in dist_git_merge_changes
    super(RhelImageRebuilder, self).dist_git_merge_changes(rebase)
  File "/home/phracek/.local/lib/python3.12/site-packages/container_workflow_tool/main.py", line 578, in dist_git_merge_changes
    self.distgit.dist_git_merge_changes(images, rebase)
  File "/home/phracek/.local/lib/python3.12/site-packages/container_workflow_tool/distgit.py", line 99, in dist_git_merge_changes
    self.pull_upstream(component, path, url, repo, ups_name, commands)
  File "/home/phracek/.local/lib/python3.12/site-packages/container_workflow_tool/git_operations.py", line 259, in pull_upstream
    self.sync_handler.handle_dangling_symlinks(cp_path, component)
  File "/home/phracek/.local/lib/python3.12/site-packages/container_workflow_tool/sync.py", line 101, in handle_dangling_symlinks
    os.readlink(src_path_content))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'upstreams/nginx/1.24/results/test/run-openshift'
```

### CODE REVIEW

**Comment by phracek** [comment]
rebased against master #86 

/test

**Comment by phracek** [comment]
> Code change looks fine to me.
> I would appreciate seeing better documentation of the specific use case this is fixing in commit message and comment/debug message inside the code.
> Specifically that the corner case we hit here happens when a symlink is removed in upstream repository but is still present in downstream repository. CWT then finds the existing downstream symlink, tries to look for it upstream and fails to do so. The fix here is ignoring the failure as we have already unlinked the symlink in preparation for the eventual copy.

@pkubatrh I have updated as code as a commit message with a detailed description.
Thanks for the review.

**Review by pkubatrh — APPROVED** [review]

**Pull request merged**
