### PR TITLE
Add Fedora config

### PR DESCRIPTION
**Pull request by omron93**
Add configuration for pulling changes from github.com/sclorg/ repositories into Fedora.

Lines beginning with `##-VERSION` means that given Fedora release has package version VERSION and that this version is not in github repo yet.

@pkubatrh Any suggestions how to do it better are welcomed. Thanks.

### CODE REVIEW

**Comment by pkubatrh** [comment]
Looking at the diffs between each fedora config - its mostly just Fedora version differences for the FROM-modifying command. eg.
```
@@ -304,9 +304,8 @@
     user: "pkubat"
     commands:
       2: "make core/root/help.1"
-      3: "sed -i s|registry.fedoraproject.org/fedora:[0-9]*|registry.fedoraproject.org/fedora:29| core/Dockerfile.fedora"
-      4: "sed -i s|registry.fedoraproject.org/f[0-9]*/|registry.fedoraproject.org/f29/| base/Dockerfile.fedora"
-      5: "cat core/Dockerfile.fedora"
+      3: "sed -i s|registry.fedoraproject.org/fedora:[0-9]*|registry.fedoraproject.org/fedora:28| core/Dockerfile.fedora"
+      4: "sed -i s|registry.fedoraproject.org/f[0-9]*/|registry.fedoraproject.org/f28/| base/Dockerfile.fedora"
```
How about using a similar system as in branches (basically s/FEDORA/config.releases.fedora.current/) for the commands as well? This would allow us to have a single fedora config with different fedora-versioned sets.

Also the default config files now live inside `container_workflow_tool/config/`

**Comment by omron93** [comment]
> How about using a similar system as in branches (basically s/FEDORA/config.releases.fedora.current/) for the commands as well?

This would be great. Where is this implemented?

Also is it possible to generate `help.1` for all versions by one command? (I'm not experienced make user and don't know if it's even possible?)

>This would allow us to have a single fedora config with different fedora-versioned sets.

There have to be differences in `git_path`. It is possible to merge all configs into one, but there won't be a big length saving. So I thought that separated files are easier to read and maintain. But I don't want to break a "consistency" of the tool, so decision is yours.

**Comment by pkubatrh** [comment]
> This would be great. Where is this implemented?

Over here for branches:
https://github.com/sclorg/container-workflow-tool/blob/master/container_workflow_tool/config.py#L55
But that would only be useful when thinking about reusing the same image definitions across different releases.
Maybe touching the FROM command in the Dockerfile directly by cwt (based on the release value in config) inside the distgit module would be a better approach. One would just need to check what base image to use (fedora base vs. s2i-core vs. s2i-base).

> Also is it possible to generate `help.1` for all versions by one command? (I'm not experienced make user and don't know if it's even possible?)

I don't think we have a general make rule for making all of the help files at once inside the common scripts. It is only used as a dependency during the build rules.

> There have to be differences in `git_path`. It is possible to merge all configs into one, but there won't be a big length saving. So I thought that separated files are easier to read and maintain. But I don't want to break a "consistency" of the tool, so decision is yours.

Ah right I missed that ... That said I think we are going to run into this git_path issue soon anyway, due to being able to maintain multiple versions for a given Fedora release thanks to modularity. But I agree that in this case it might be easier to maintain separate config files per Fedora release.

Maybe we could at least share some of the duplicit content (mails, urls, etc.)? Not sure if yaml allows for some sort of "include" of shared code however.

**Comment by omron93** [comment]
> But that would only be useful when thinking about reusing the same image definitions across different releases
> .......................
> I don't think we have a general make rule for making all of the help files at once inside the common scripts. It is only used as a dependency during the build rules.

And how this rule could look like? This would be also useful to share commands blocks for most of the config.

> Maybe we could at least share some of the duplicit content (mails, urls, etc.)? Not sure if yaml allows for some sort of "include" of shared code however.

I thing it's not easily possible by yaml. Does it worth to implement it in cwt?

**Comment by pkubatrh** [comment]
Changes to cwt lgtm. I have merged in #3 which introduced the `!include` statement for config bits sharing. Can you modify the configs accordingly?

As stated in #3 the `!include` statement has to be used as a value of a key - `key: !include file.yaml` includes all of the contents of `file.yaml` under `key`, while `!include file.yaml:shared_key` only includes the values of `shared_key`.

**Comment by pkubatrh** [comment]
lgtm, lets get this merged in

**Pull request merged**
