### PR TITLE
Enable nginx and nodejs sources

### PR DESCRIPTION
**Pull request by phracek**
The commit enables nginx and nodejs containers.
The versions are updated.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
Nginx container still does not have version 1.18. The latest version in Nginx is 1.16. https://github.com/sclorg/nginx-container/blob/master/Makefile#L3. 

Wait for clarifying if it is feasible to add the new version into nginx container.

**Comment by phracek** [comment]
Nginx in version 1.18 is already present in nginx-container. https://github.com/sclorg/nginx-container/pull/115

**Comment by phracek** [comment]
@pkubatrh Please look at it. And let me know if you need some fixes ;)

**Comment by pkubatrh** [comment]
LGTM, removed `WIP` from the title as I expect it is already prepared for merging

**Pull request merged**
