### PR TITLE
Use property decorators

### PR DESCRIPTION
**Pull request by phracek**
This pull request removes decorators instead of introducing property.
https://www.pythontutorial.net/python-oop/python-property-decorator/

### CODE REVIEW

**Comment by phracek** [comment]
I need to check this change in real workflow, but it should not brake any functionality.

**Comment by phracek** [comment]
I have done some steps with real workflow and everything is working properly
```bash
rhcwt -v 5 --tmp /tmp/$TMP_DIR2 git clonedownstream
Using working directory: /tmp/something
Cloning into: containers/s2i-core
Cloning into: containers/s2i-base
Cloning into: containers/mariadb-103
Cloning into: containers/mariadb-105
Cloning into: containers/mysql-80
Cloning into: containers/nginx-118
Cloning into: containers/nginx-120
Cloning into: containers/postgresql-10
Cloning into: containers/postgresql-12
Cloning into: containers/postgresql-13
Cloning into: containers/redis-5
Cloning into: containers/redis-6
Cloning into: containers/httpd-24
Cloning into: containers/varnish-6
Cloning into: containers/nodejs-14
Cloning into: containers/nodejs-16
Cloning into: containers/php-74
Cloning into: containers/php-80
Cloning into: containers/python-27
Cloning into: containers/python-36
Cloning into: containers/python-38
Cloning into: containers/python-39
Cloning into: containers/perl-526
Cloning into: containers/perl-530
Cloning into: containers/perl-532
Cloning into: containers/ruby-25
Cloning into: containers/ruby-27
Cloning into: containers/ruby-30
Cloning into: containers/nodejs-10

```

**Review by zmiklank — APPROVED** [review]
Thanks for the PR, LGTM.

I, however, was able to review this PR only with the eyes of a person, who understood Python's property decorators a few minutes ago :).

**Pull request merged**
